### ISSUE TITLE
Problème de parsing?

### ISSUE THREAD

**Issue by RolluS** [lunarok/jeedom_rflink#10]
Après installation correcte des dépendances et lancement du démon sur un Jeedom 3.2.2 avec RFLink 2018-04-01 07:11:28, le log révèle un problème de parsage des données, et les infos contenues dans les objets RFLink sont donc erronées.

Ce qui est relevé (rflink_node):
```
Mon Apr 02 2018 19:29:10 GMT+0000 (UTC) - Send Value : 20;2B;Oregon 
Mon Apr 02 2018 19:29:10 GMT+0000 (UTC) - Send Value : TempHygro;ID=428F3;TEMP=
Mon Apr 02 2018 19:29:10 GMT+0000 (UTC) - Send Value : 00f7;HUM=48;HSTATUS=1;BAT
Mon Apr 02 2018 19:29:10 GMT+0000 (UTC) - Send Value : =OK;
```
Au lieu de:
```
Mon Apr 02 2018 19:29:10 GMT+0000 (UTC) - Send Value : 20;2B;Oregon TempHygro;ID=428F3;TEMP=00f7;HUM=48;HSTATUS=1;BAT=OK;
```

Les fin de chaines (retours à la ligne dans le log) sont aléatoires.

Il s'agit d'un système en prod (chauffage), merci d'avance pour ton aide!

**Comment by lunarok** [comment]
le support c'est sur le forum

**Comment by RolluS** [comment]
Donc c'est pas un bug? 

Le même problème avait été rapporté par des utilisateurs avec des RFLink en Ethernet, cela a été corrigé avec une maj, je croyais que c'était similaire, désolé.

Merci et bonne continuation
